In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame
import matplotlib.pyplot as plt

In [2]:
obj = Series([4, 7, -5, 3])

In [3]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj2 = Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [7]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [8]:
obj2[-1]

3

In [9]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [10]:
obj[:-1]

0    4
1    7
2   -5
dtype: int64

In [11]:
obj[2:3]

2   -5
dtype: int64

In [12]:
obj[1:]

1    7
2   -5
3    3
dtype: int64

In [13]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [14]:
obj2['c']

3

In [15]:
obj2[2]

-5

In [16]:
obj2[1:]

b    7
a   -5
c    3
dtype: int64

In [17]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [18]:
obj2 * 2.

d     8.0
b    14.0
a   -10.0
c     6.0
dtype: float64

In [19]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [20]:
'b' in obj2

True

In [21]:
'j' in obj2

False

In [22]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [23]:
obj3 = Series(sdata)

In [24]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [25]:
obj3['Utah']

5000

In [26]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [27]:
obj4 = Series(sdata, index=states)

In [28]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [29]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [30]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [31]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [32]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [33]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [34]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [35]:
obj4.name = 'population'

In [36]:
obj4.index.name = 'state'

In [37]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [38]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [39]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [40]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}

In [41]:
frame = DataFrame(data)

In [42]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [43]:
frame['state'][:-1]

0      Ohio
1      Ohio
2      Ohio
3    Nevada
Name: state, dtype: object

In [44]:
DataFrame(data, columns=['year', 'pop', 'state'])

year  pop   state
0  2000  1.5    Ohio
1  2001  1.7    Ohio
2  2002  3.6    Ohio
3  2001  2.4  Nevada
4  2002  2.9  Nevada

In [45]:
frame2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                   index=['one', 'two', 'three', 'four', 'five'])

In [46]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [47]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [48]:
frame2.index

Index(['one', 'two', 'three', 'four', 'five'], dtype='object')

In [49]:
frame2['year']

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [50]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [51]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [52]:
frame2.ix['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [53]:
frame2['debt'] = 16.5

In [54]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [55]:
frame2['debt'] = np.arange(5)

In [56]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4

In [57]:
val = Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [58]:
frame2['debt'] = val

In [59]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [60]:
frame2['eastern'] = frame2.state == 'Ohio'

In [61]:
frame2

year   state  pop  debt eastern
one    2000    Ohio  1.5   NaN    True
two    2001    Ohio  1.7  -1.2    True
three  2002    Ohio  3.6   NaN    True
four   2001  Nevada  2.4  -1.5   False
five   2002  Nevada  2.9  -1.7   False

In [62]:
del frame2['eastern']

In [63]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [64]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [65]:
frame3 = DataFrame(pop)

In [66]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [67]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [68]:
DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [69]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}

In [70]:
DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [71]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [72]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [73]:
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [74]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

In [75]:
obj = Series(range(3), index=['a', 'b', 'c'])

In [76]:
obj

a    0
b    1
c    2
dtype: int32

In [77]:
index = obj.index

In [78]:
index

Index(['a', 'b', 'c'], dtype='object')

In [79]:
index[1:]

Index(['b', 'c'], dtype='object')

In [80]:
index[-1]

'c'

In [81]:
index = pd.Index(np.arange(3))

In [82]:
index

Int64Index([0, 1, 2], dtype='int64')

In [83]:
obj2 = Series([1.5, -2.5, 0], index=index)

In [84]:
obj2.index is index

True

In [85]:
'Ohio' in frame3.columns

True

In [86]:
2003 in frame3.index

False